[build]
  command = "npm run build"
  pubilsh = "src"
  functions = "lambda"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true
