[build]
  command = "npm run build && npm run build:lambda"
  pubilsh = "public"
  functions = "./lambda"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true
